---
# tasks file for ansible-vcd
- name: Create VM
  vca_vapp:
    state: present
    operation: noop 

    host: "{{ vcd_url }}"
    org: "{{ org_name }}"
    vdc_name: "{{ vdc_name }}"
    username: "{{ vcd_username }}"
    password: "{{ vcd_pwd }}"
    api_version: '5.6'
    service_type: vcd

    catalog_name: "{{ vcd_catalog }}"
    template_name: "{{ vcd_os_template }}"

    vapp_name: "{{ vm_name }}"
    vm_name: "{{ vm_name }}"
    vm_cpus: "{{ vm_cpu }}"
    vm_memory: "{{ vm_mem }}"
    network_name: "{{ vm_net }}"

  register: vapp

#- debug:
#        msg: "VM {{ inventory_hostname }} got IP {{vm_ip}}"

- name: PowerOn VM
  vca_vapp:
    state: present
    operation: poweron

    host: "{{ vcd_url }}"
    org: "{{ org_name }}"
    vdc_name: "{{ vdc_name }}"
    username: "{{ vcd_username }}"
    password: "{{ vcd_pwd }}"
    api_version: '5.6'
    service_type: vcd

    vapp_name: "{{ vm_name }}"

- name: Waiting for VM to boot (min 90s)
  wait_for:
    port: 22
    host: "{{ vm_ip }}"
    search_regex: SSH
    #delay: 90
    #Sleep available from version 2.3
    #sleep: 10

- name: get SSH public key
  shell: "ssh-keyscan {{ vm_ip }} | grep -v  '#.*' | head -1"
  register: keyscan
  changed_when: False

#- debug:
#        msg: "key {{ keyscan }}"

- name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
  known_hosts:
    name: "{{ vm_ip }}"
    key: "{{ keyscan.stdout }}"
    path: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
  when: 
    - not keyscan | skipped

- name: Trying to log into VM (using ssh key)
  ping:
  register: test_login

#- name: Setting Hostname
#  delegate_to: "{{ vm_name }}"
#  hostname:
#    name: "{{ vm_name }}"

